steps:
- task: PowerShell@2
  displayName: 'Install SoapUI'
  inputs:
    targetType: 'inline'
    script: |
      # Download the SoapUI installer
      $soapuiUrl = "https://dl.eviware.com/soapuios/5.7.2/SoapUI-x64-5.7.2.exe"
      $installerPath = "$env:USERPROFILE\Downloads\SoapUIInstaller.exe"
      Invoke-WebRequest -Uri $soapuiUrl -OutFile $installerPath

      # Silent installation
      Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait

      # Verify installation
      Write-Output "SoapUI installed successfully."