trigger:
- main  # Adjust the branch as needed

pool:
  vmImage: 'windows-latest'  # Use 'ubuntu-latest' for Linux

steps:
# Install SoapUI (if not already available)
- task: PowerShell@2
  displayName: 'Install SoapUI'
  condition: eq(variables['Agent.OS'], 'Windows')
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Downloading and Installing SoapUI..."
      Invoke-WebRequest -Uri "https://dl.eviware.com/soapui/5.7.0/SoapUI-x64-5.7.0.exe" -OutFile "$env:USERPROFILE\Downloads\SoapUI.exe"
      Start-Process -FilePath "$env:USERPROFILE\Downloads\SoapUI.exe" -ArgumentList "/S" -Wait

# Run SoapUI Tests
- task: PowerShell@2
  displayName: 'Run SoapUI Tests'
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Running SoapUI Tests..."
      testrunner.bat -r -j -f"$(Build.ArtifactStagingDirectory)\Reports" "$(Build.SourcesDirectory)\MySoapUIProject.xml"

# Publish Test Results
- task: PublishTestResults@2
  displayName: 'Publish SoapUI Test Results'
  inputs:
    testResultsFiles: '$(Build.ArtifactStagingDirectory)\Reports\*.xml'
    testRunTitle: 'SoapUI Test Results'